/******************************************************************************
* FORMULA NAME      : GB_CMP_TIPO_CONTRATO_DESC_R4                          *
* FORMULA TYPE      : Compensation Default and Override                       *
* DESCRIPTION       : Retorna la descripcion del tipo de contrato             *
*                     del colaborador a partir de PER_ASG_ATTRIBUTE1.         *
*-----------------------------------------------------------------------------*
* CREATED BY        : IT-GLOBAL                                               *
* CREATION DATE     : 08-Junio-2026                                           *
* LAST UPDATE DATE  : 08-Junio-2026                                           *
*-----------------------------------------------------------------------------*
* Change History:                                                             *
* Author          | Date            | Ver | Comments                          *
*-----------------+-----------------+-----+-----------------------------------*
* IT Global       | 08-Junio-2026   |  1  | Version Inicial                   *
* IT Global       | 08-Junio-2026   |  2  | Mapeo completo ESP/MOR/PT         *
******************************************************************************/

INPUTS ARE CMP_IV_PLAN_START_DATE (text),
CMP_IV_PLAN_END_DATE (text),
CMP_IVR_ASSIGNMENT_ID (NUMBER_NUMBER),
CMP_IV_PLAN_EXTRACTION_DATE (text)

DEFAULT FOR PER_ASG_ATTRIBUTE1 IS 'N/A'

HR_EXTRACT_DATE = TO_DATE(CMP_IV_PLAN_EXTRACTION_DATE, 'YYYY/MM/DD')

l_log = SET_LOG('*** INICIO GB_CMP_TIPO_CONTRATO_DESC_R4 ***')

CHANGE_CONTEXTS(EFFECTIVE_DATE = HR_EXTRACT_DATE)
(
    L_CODE = PER_ASG_ATTRIBUTE1
)

l_log = SET_LOG('Attribute1 raw: ' || L_CODE)

IF L_CODE = '000' THEN
    L_DESC = 'SIN CONTRATO (TEMPORAL)'
ELSE IF L_CODE = '011' THEN
    L_DESC = 'SIN CONTRATO (INDEFINIDO)'
ELSE IF L_CODE = '100' THEN
    L_DESC = 'ORDINARIO INDEFINIDO'
ELSE IF L_CODE = '109' THEN
    L_DESC = 'INDEFINIDO TP COMPL TRANSF TEMPORAL'
ELSE IF L_CODE = '130' THEN
    L_DESC = 'MINUSVALIDOS INDEFINIDO TIEMPO COMP'
ELSE IF L_CODE = '139' THEN
    L_DESC = 'MINUSV. CONVERS. INDEFINIDO TP COMP'
ELSE IF L_CODE = '150' THEN
    L_DESC = 'INDEFINIDO TIEMPO COMPLETO'
ELSE IF L_CODE = '189' THEN
    L_DESC = 'INDEFINIDO TP COMPL TRANSF DE TEMPO'
ELSE IF L_CODE = '200' THEN
    L_DESC = 'ORDINARIO INDEFINIDO TIEMPO PARCIAL'
ELSE IF L_CODE = '209' THEN
    L_DESC = 'INDEFINIDO TP PARC TRANSF DE TEMPOR'
ELSE IF L_CODE = '230' THEN
    L_DESC = 'MINUSVALIDOS INDEFINIDO TIEMPO PARC'
ELSE IF L_CODE = '239' THEN
    L_DESC = 'MINUSV. CONVERS. INDEFIDO TP PARCIA'
ELSE IF L_CODE = '250' THEN
    L_DESC = 'INDEFINIDO TP PARCIAL INICIAL'
ELSE IF L_CODE = '289' THEN
    L_DESC = 'INDEFINIDO TP PARC TRANSF DE TEMPOR'
ELSE IF L_CODE = '300' THEN
    L_DESC = 'INDEFINIDO FIJO/DISCONTINUO'
ELSE IF L_CODE = '309' THEN
    L_DESC = 'INDEFINIDO FIJO/DISC TRANSF DE TEMP'
ELSE IF L_CODE = '330' THEN
    L_DESC = 'MINUSVALIDOS INDEFINIDO FIJO DISCON'
ELSE IF L_CODE = '350' THEN
    L_DESC = 'INDEFINIDO FIJO/DISC'
ELSE IF L_CODE = '389' THEN
    L_DESC = 'INDEFINIDO FIJ/DISC TRANSF CONT TEM'
ELSE IF L_CODE = '401' THEN
    L_DESC = 'POR OBRA O SERVICIO DETERM TP COMPL'
ELSE IF L_CODE = '402' THEN
    L_DESC = 'EVENTUAL CIRCUNSTAN PRODUCC TP COMP'
ELSE IF L_CODE = '403' THEN
    L_DESC = 'DURACION DETERM INSERCION TP COMPL'
ELSE IF L_CODE = '408' THEN
    L_DESC = 'TEMPORAL TP COMPLETO CARACTER ADMVO'
ELSE IF L_CODE = '410' THEN
    L_DESC = 'DURAC DETERM DE INTERINIDAD TP COMP'
ELSE IF L_CODE = '418' THEN
    L_DESC = 'TEMPOR INTERINID TP COMP CARAC ADMV'
ELSE IF L_CODE = '420' THEN
    L_DESC = 'TEMPORAL PRACTICAS A TIEMPO COMPLET'
ELSE IF L_CODE = '421' THEN
    L_DESC = 'TEMPORAL FORMACION TIEMPO COMPLETO'
ELSE IF L_CODE = '430' THEN
    L_DESC = 'TEMPORAL MINUSV.TIEMPO COMPLETO'
ELSE IF L_CODE = '441' THEN
    L_DESC = 'TEMPORAL RELEVO TIEMPO COMPLETO'
ELSE IF L_CODE = '450' THEN
    L_DESC = 'TEMPOR TPO COMPL FOMENTO EMPLEO'
ELSE IF L_CODE = '501' THEN
    L_DESC = 'POR OBRA O SERVICIO DETERM TP PARCI'
ELSE IF L_CODE = '502' THEN
    L_DESC = 'EVENTUAL CIRCUNSTAN PRODUCC TP PARC'
ELSE IF L_CODE = '503' THEN
    L_DESC = 'DURACION DETERM INSERCION TP PARCIA'
ELSE IF L_CODE = '508' THEN
    L_DESC = 'TEMPORAL TPO PARCIAL DE CARACT ADMV'
ELSE IF L_CODE = '510' THEN
    L_DESC = 'DURAC DETERM INTERINIDAD TIEMP PARC'
ELSE IF L_CODE = '518' THEN
    L_DESC = 'TEMPOR INTERINID TP PARC CARACT ADM'
ELSE IF L_CODE = '520' THEN
    L_DESC = 'TEMPORAL PRACTICAS TIEMPO PARCIAL'
ELSE IF L_CODE = '530' THEN
    L_DESC = 'TEMPORAL MINUSVALIDOS TIEMPO PARCIA'
ELSE IF L_CODE = '540' THEN
    L_DESC = 'JUBILADO TIEMPO PARCIAL'
ELSE IF L_CODE = '541' THEN
    L_DESC = 'TEMPORAL RELEVO TIEMPO PARCIAL'
ELSE IF L_CODE = '550' THEN
    L_DESC = 'TEMP TPO PARCIAL FOMENTO EMPLEO'
ELSE IF L_CODE = 'BAUK01' THEN
    L_DESC = 'BARCEL UK'
ELSE IF L_CODE = 'BUK01' THEN
    L_DESC = 'UK'
ELSE IF L_CODE = 'MA01' THEN
    L_DESC = 'CDD'
ELSE IF L_CODE = 'MA02' THEN
    L_DESC = 'CDI'
ELSE IF L_CODE = 'MA03' THEN
    L_DESC = 'ANAPEC'
ELSE IF L_CODE = 'PT01' THEN
    L_DESC = 'ACTIVO EFECTIVO'
ELSE IF L_CODE = 'PT02' THEN
    L_DESC = 'CONTRATO A TERMO INCERTO'
ELSE IF L_CODE = 'PT03' THEN
    L_DESC = 'CONTRATO A TERMO CERTO'
ELSE IF L_CODE = 'TAE' THEN
    L_DESC = 'CONTRATO DE TRABAJADORES AUTONOMOS ECONOMICAMENTE DEPENDIENTES'
ELSE
    L_DESC = L_CODE

l_log = SET_LOG('*** RESULTADO TIPO_CONTRATO_DESC: ' || L_DESC || ' ***')

RETURN L_DESC