Name: GB_CMP_RATE_ID_VALUE_MIN
Description: Obtiene el valor mínimo de una tarifa específica para un grado y fecha.    
SELECT 
V.MINIMUM
FROM
PER_RATES_F R, PER_RATE_VALUES_F V
WHERE 
R.RATE_ID = V.RATE_ID
AND V.RATE_OBJECT_ID = :{PARAMETER.P_ASSIGNMENT_GRADE}
AND V.RATE_ID = :{PARAMETER.P_ASSIGNMENT_RATE}
AND :{PARAMETER.P_EFFECTIVE_DATE} BETWEEN R.EFFECTIVE_START_DATE AND R.EFFECTIVE_END_DATE
AND  :{PARAMETER.P_EFFECTIVE_DATE} BETWEEN V.EFFECTIVE_START_DATE AND V.EFFECTIVE_END_DATE