Name : GB_CMP_ASG_RATE_ID
Description : Obtiene el ID de la tarifa asignada a un grado y asignación en una fecha específica.
SELECT A.GRADE_RATE_ID
FROM
CMP_SALARY_BASES A, CMP_SALARY B	
WHERE 	
A.SALARY_BASIS_ID = B.SALARY_BASIS_ID
AND B.PERSON_ID = :{PARAMETER.PERSON_ID}
AND B.ASSIGNMENT_ID = :{PARAMETER.P_ASSIGNMENT_ID}
AND TO_DATE(:{PARAMETER.P_EFFECTIVE_DATE}, 'YYYY/MM/DD') BETWEEN B.DATE_FROM AND B.DATE_TO

